package com.example.demo.enums

enum class Permisson {
 EDIT_MY_NAME,
 ADD_EMPLOYEE,
 EDIT_EMPLOYEE,
 DELETE_EMPLOYEE,
 VIEW_EMPLOYEE,
 ADD_RANK,
 EDIT_RANK,
 DELETE_RANK,
 VIEW_RANK,
 ADD_PROJECT,
 EDIT_PROJECT,
 DELETE_PROJECT,
 VIEW_PROJECT
}